// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayLess.Data;

#nullable disable

namespace PayLess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240205142413_addupdates0502")]
    partial class addupdates0502
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("PayLess.Models.EstoqueLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdLoja")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EstoqueLojas");
                });

            modelBuilder.Entity("PayLess.Models.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereço")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("PayLess.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estoque")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstoqueLojaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueLojaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("PayLess.Models.Produto", b =>
                {
                    b.HasOne("PayLess.Models.EstoqueLoja", null)
                        .WithMany("Produtos")
                        .HasForeignKey("EstoqueLojaId");
                });

            modelBuilder.Entity("PayLess.Models.EstoqueLoja", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
